### ISSUE TITLE
Question for DSPi - Which Soundcard did you use?

### ISSUE THREAD

**Issue by spectralLight** [dddomin3/DSPi#41]
Hello

which soundcard for the rpi3 did you use to connect your guitar? Did it have mono-jack input?

i use the stereo soundcard from audio inejctor and connected it like this:
guitar Input over mono-Jack to spdif-output -> Input over spdif of soundcard

Do you see any problems with spdif in implementing your project? 

thx in advance for your answer

**Comment by dddomin3** [comment]
I used the behringer uca222 I think it's called? Usb $20 on Amazon compliant sound card.

**Comment by dddomin3** [comment]
Not sure how spdif works honestly, I just used trs connector

**Comment by dddomin3** [comment]
As long as jackd can see the spdif, it'll work. Depends on the Linux audio stack really

**Comment by dddomin3** [comment]
I'd test it on like Ubuntu studio, and it should with raspi a similar way

**Comment by dddomin3** [comment]
How's this working out for you? I want to close the issue if you got your question answered :)

**Comment by spectralLight** [comment]
Oh sorry, everything is working. Thx for your answers. I did it different. But your project helped me alot to get inspiration. Thx a lot. You can close the issue.

**Comment by dddomin3** [comment]
Awesome! That's exactly why I have the repo. Glad I helped!
